name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npx prisma generate --schema=./prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_FILENAME: ${{ secrets.DATABASE_FILENAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CACHE_DATABASE_PATH: ${{ secrets.CACHE_DATABASE_PATH }}
          LITEFS_DIR: ${{ secrets.LITEFS_DIR }}
